### ISSUE TITLE
No example of "declare" statement anywhere

### ISSUE THREAD

**Issue by dogboydog** [YarnSpinnerTool/YSDocs#12]
Would probably make sense to add something here 

https://docs.yarnspinner.dev/getting-started/writing-in-yarn/logic-and-variables

**Comment by jorgenbuilder** [comment]
+1. I actually couldn't find a single example of this anywhere. It's mentioned elsewhere in the docs, which got me curious about the feature.

**Comment by desplesda** [comment]
This is now addressed [in our documentation](https://docs.yarnspinner.dev/getting-started/writing-in-yarn/logic-and-variables#declaring-variables)! Thanks for the report.
