### ISSUE TITLE
YarnSpinner for Godot doc misses Quick Start / Getting Started / tutorial-style instructions

### ISSUE THREAD

**Issue by hsandt** [YarnSpinnerTool/YSDocs#50]
I was following the old v2.3 doc https://docs.yarnspinner.dev/v/2.3/beginners-guide/making-a-game/yarn-spinner-for-unity which was a long page, but had the advantage of being pragmatic and getting you started with some actual piece of dialogue to show.

Now I switched to the new doc https://docs.yarnspinner.dev/using-yarnspinner-with-godot/overview which has a full section "YARN SPINNER FOR GODOT" dedicated to Godot, and split into several pages, but except the first pages, they are really hard doc as opposed to Getting Started tutorials. So, I have no idea when I will get to a point where I'll actually have some dialogue playing in the game.

I couldn't find 3rd party tutorial videos either so for now I'm sticking to the 2.3 doc and hope it's compatible with 2.4.

Unity has a similar issue but the doc seems to go more in depth in settings things up, *and* there is a bigger amount of third-party tutorials for Unity.

**Comment by hsandt** [comment]
I kept following the 2.3 tutorial and I'm hitting some hurdles, including a blocking one:

- the instantiated DefaultDialogueSystem.tscn nide hierarchy doesn't show until I right-click > check Editable Children. This is important to show the DialogueRunner and assign some dialogue tree resource. That was easy.
- I created a new YarnProject *resource* as asked but it shows a warning:

![image](https://github.com/YarnSpinnerTool/YSDocs/assets/1067772/247fcd9c-dcf2-4623-8af7-ec676dc35418)

I have already created my .yarnproject file following the 2.4 tutorial, but the latter doesn't say how to *generate* the .tres Yarn Project *resource* from the .yarnproject tile. So I'm stuck and I don't even know how to use the DefaultDialogueSystem.tscn 's DialogueRunner to run my dialogue tree.

I'm not even sure if going back to v2.3 will be helpful. I don't see anything in the changelog saying that the warning was recently added and that the Yarn Project resource creation pipeline changed.

**Comment by dogboydog** [comment]
Hi, 
Apologize for any misunderstandings here but I can clarify. 

There is still a getting started for Godot page in the same category as the getting started for Unity link; it was not removed, and contains the updated information for creating yarn projects. The Godot overview should maybe link to it, although the equivalent Unity page does not seem to link to the Unity beginner's guide.  
https://docs.yarnspinner.dev/beginners-guide/making-a-game/yarn-spinner-for-godot 

The changes to how Yarn projects work in Godot are described in detail here - this happened in version 0.2.0 https://github.com/YarnSpinnerTool/YarnSpinner-Godot/blob/develop/CHANGELOG.md   
In short, you don't create .tres YarnProjects at all anymore, you just create .yarnproject files and .tres files are generated in the .godot folder behind the scenes.  You use the .yarnproject file to drag and drop into the DialogueRunner.
 
I agree the beginner's guide should mention the editable children menu item when  you instantiate the dialogue system. I can add that. 

You should only use the current  live documentation for the current version of the plugin. Going back to previous versions will not be accurate when using the current version of the plugin
 

The Godot plugin is in a pre-release state and does not release with the same versioning cadence or version numbers as the Unity plugin, so version 2.4 of unity does not correspond to version 0.2.4 of the Godot plugin for example — the resemblance is only coincidental. Maybe I could update the 2.3 page with a note explaining the last plugin version it's compatible with.

**Comment by dogboydog** [comment]
I think I've addressed everything here with #51, #52, and #53, but let me know if you feel otherwise.

**Comment by dogboydog** [comment]
Thanks. You don't need to do anything manually with the . tres file in the godot folder. You just work directly with the . yarnproject file. The .tres file is just used "behind the scenes" to store generated data related to your yarn files.

**Comment by dogboydog** [comment]
Thanks. You don't need to do anything manually with the . tres file in the godot folder. You just work directly with the . yarnproject file. The .tres file is just used "behind the scenes" to store generated data related to your yarn files.

**Comment by dogboydog** [comment]
Note: It looks like it's not possible to quick load custom c# resources right now, so users have to drag and drop the . yarnproject file 

`https://github.com/godotengine/godot/issues/86060`
